export const actionType = {
    FETCHINGSTART: "FETCHINGSTART",
    FETCHINGSUCCESS: "FETCHINGSUCCESS",
    FETCHINGERROR: "FETCHINGERROR",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
}